export const TextList = [
    "Text to type",
    // "k'/'if",
    "This is Prashanna Paudel",
    // "Nepal is a small but a beautiful country",
    // "We Nepales live in peace and harmony with each other",
    "tire ter tire irreline tire irrel err ner retine err ter",
    "trient err tire relier ner irrient ner ret irrientine ",
    "ter irrient tre tire ner err tire ter err ter err tire",
    "ner tree ner tir irriet ter irrienten tirine trient tre",
    "ren tire ner errent trient tre irrentle tret erren ere",
    "irrent irren trient irrel irrie ner ter err ner ter ner",
    "irrent irrin errel erren irrel irrient err tire errelie",
    "ter irrent errien ter irrient err ner ter tree tire",
    "ner erreline errient ter tire ter err irrelie ter relier",
    "irrient irrieter tire errent irrelie irrient trient err ter",
    "a student should never confine himself to his schoolbooks only",
    "errient errel ret irrient terren tere ner irrelie ter irriet",
    "errent ner irriet ere triet trient irrient irren ner triet",
    "err tire relet erret err tire ner errent erren trient ner",
    "tire ner tir irrel tire irrelin irrelet ter irrel ter ner ter",
    "trient irrel ner tree tire tirelie tere err trient erren",
    "ner triet tire err triet ter ere ner errent irrient ter rent",
    "irrient tire err irrient tren irrient ter irrelet ter irrent",
    "ner irrient reline ter ner retter ner ren errent irrentin",

]