export const TextList = [
    "Text to type",
    "This is Prashanna Paudel",
    "tire ter tire irreline tire irrel err ner retine err ter",
    "trient err tire relier ner irrient ner ret irrientine ",
    "ter irrient tre tire ner err tire ter err ter err tire",
    "ner tree ner tir irriet ter irrienten tirine trient tre",
    "ren tire ner errent trient tre irrentle tret erren ere",
    "irrent irren trient irrel irrie ner ter err ner ter ner",
    "irrent irrin errel erren irrel irrient err tire errelie",
    "ter irrent errien ter irrient err ner ter tree tire",
    "ner erreline errient ter tire ter err irrelie ter relier",
    "irrient irrieter tire errent irrelie irrient trient err ter",
    "a student should never confine himself to his schoolbooks only.",
]